FROM mcr.microsoft.com/dotnet/sdk:8.0 AS migration

RUN dotnet tool install --global dotnet-ef --version 9.0.0

WORKDIR /
COPY . .

ENV ConnectionStrings__DBConnection="Host=container-postgres;Database=inff_database;Username=postgres;Password=password"
ENV ASPNETCORE_ENVIRONMENT=Development
# PATH for dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

WORKDIR /src
ENTRYPOINT ["/bin/bash", "-c", "\  
  echo 'Building the project...' && \
  dotnet build InnovateFuture.Api/InnovateFuture.Api.csproj --verbosity:diagnostic && \
  dotnet build InnovateFuture.Infrastructure/InnovateFuture.Infrastructure.csproj --verbosity:diagnostic && \
  echo 'Running database migrations...' && \
  echo 'Service metadata URI:' $ECS_CONTAINER_METADATA_URI && \
  echo 'DB Connection String:' $ConnectionStrings__DBConnection && \
  dotnet ef database update \
  --project InnovateFuture.Infrastructure/InnovateFuture.Infrastructure.csproj \
  --startup-project InnovateFuture.Api/InnovateFuture.Api.csproj \
  --verbose"]