version: '3.8'

services:
  postgres:
    image: postgres:17.2
    container_name: test-postgres
    environment:
      POSTGRES_DB: InnovateFuture
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: 123321abb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_admin -d InnovateFuture"]
      interval: 5s
      timeout: 5s
      retries: 5

  tests:
    image: inff-api-build:latest
    container_name: test-runner
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: InnovateFuture
      DB_USER: db_admin
      DB_PASS: 123321abb
      ASPNETCORE_ENVIRONMENT: Testing
    volumes:
      - ./tests:/tests
    command: >
      dotnet test "/src/InnovateFuture.Api.Tests/InnovateFuture.Api.Tests.csproj"
      --logger "console;verbosity=detailed"
