<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InnovateFuture.Infrastructure\InnovateFuture.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.400" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.415" />
    <PackageReference Include="Handlebars.Net" Version="2.1.6" />
    <PackageReference Include="MailKit" Version="4.10.0" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="LinqKit.Microsoft.EntityFrameworkCore" Version="8.1.8" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="MediatR.Contracts" Version="2.0.1" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
  </ItemGroup>

</Project>
