// <auto-generated />
using System;
using InnovateFuture.Infrastructure.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InnovateFuture.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250107083110_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Organisation", b =>
                {
                    b.Property<Guid>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("org_name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("Subscription")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subscription");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website_url");

                    b.HasKey("OrgId");

                    b.ToTable("Organisations");

                    b.HasData(
                        new
                        {
                            OrgId = new Guid("d96e643e-a7aa-42b0-a8cd-1cdd8610e857"),
                            CreatedAt = new DateTime(2025, 1, 7, 8, 31, 10, 171, DateTimeKind.Utc).AddTicks(1720),
                            OrgName = "org_name_01_test",
                            Status = (short)0,
                            UpdatedAt = new DateTime(2025, 1, 7, 8, 31, 10, 171, DateTimeKind.Utc).AddTicks(1720)
                        },
                        new
                        {
                            OrgId = new Guid("0aecbf37-ead3-470c-ad8b-790d7eea3b0a"),
                            CreatedAt = new DateTime(2025, 1, 7, 8, 31, 10, 171, DateTimeKind.Utc).AddTicks(1720),
                            OrgName = "org_name_02_test",
                            Status = (short)0,
                            UpdatedAt = new DateTime(2025, 1, 7, 8, 31, 10, 171, DateTimeKind.Utc).AddTicks(1720)
                        });
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<Guid?>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid?>("SupervisedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("supervised_by");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ProfileId");

                    b.HasIndex("InvitedBy");

                    b.HasIndex("OrgId");

                    b.HasIndex("RoleId");

                    b.HasIndex("SupervisedBy");

                    b.HasIndex("UserId", "RoleId", "OrgId")
                        .IsUnique()
                        .HasDatabaseName("IX_Profiles_user_id_role_id_org_id");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            ProfileId = new Guid("4d69456b-9b86-43b9-b8f7-09a88062eb6b"),
                            CreatedAt = new DateTime(2025, 1, 7, 8, 31, 10, 171, DateTimeKind.Utc).AddTicks(1770),
                            IsActive = true,
                            OrgId = new Guid("d96e643e-a7aa-42b0-a8cd-1cdd8610e857"),
                            RoleId = new Guid("e114c66a-07b2-4768-b0cf-c111895ce0c4"),
                            UpdatedAt = new DateTime(2025, 1, 7, 8, 31, 10, 171, DateTimeKind.Utc).AddTicks(1770),
                            UserId = new Guid("725f77b0-258a-4a92-827a-f5c4adfcba49")
                        });
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<short>("CodeName")
                        .HasColumnType("smallint")
                        .HasColumnName("code_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("RoleId");

                    b.HasIndex("CodeName")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_code_name");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_name");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("e114c66a-07b2-4768-b0cf-c111895ce0c4"),
                            CodeName = (short)0,
                            CreatedAt = new DateTime(2025, 1, 7, 8, 31, 10, 171, DateTimeKind.Utc).AddTicks(1620),
                            Description = "Responsible for managing the entire platform, including...",
                            Name = "Platform Admin",
                            UpdatedAt = new DateTime(2025, 1, 7, 8, 31, 10, 171, DateTimeKind.Utc).AddTicks(1620)
                        },
                        new
                        {
                            RoleId = new Guid("d3788298-39b4-4a40-9985-bfa6a830acd9"),
                            CodeName = (short)1,
                            CreatedAt = new DateTime(2025, 1, 7, 8, 31, 10, 171, DateTimeKind.Utc).AddTicks(1620),
                            Description = "Oversees organisational-level operations, including...",
                            Name = "Organisation Admin",
                            UpdatedAt = new DateTime(2025, 1, 7, 8, 31, 10, 171, DateTimeKind.Utc).AddTicks(1620)
                        },
                        new
                        {
                            RoleId = new Guid("3b69fda3-555a-4658-a6ab-31e1f327ef79"),
                            CodeName = (short)2,
                            CreatedAt = new DateTime(2025, 1, 7, 8, 31, 10, 171, DateTimeKind.Utc).AddTicks(1630),
                            Description = "Handles teaching-related responsibilities within the organisation, such as...",
                            Name = "Organisation Teacher",
                            UpdatedAt = new DateTime(2025, 1, 7, 8, 31, 10, 171, DateTimeKind.Utc).AddTicks(1630)
                        },
                        new
                        {
                            RoleId = new Guid("32ef6536-3cb1-4846-bd32-cd34b489fd43"),
                            CodeName = (short)3,
                            CreatedAt = new DateTime(2025, 1, 7, 8, 31, 10, 171, DateTimeKind.Utc).AddTicks(1630),
                            Description = "Allows monitoring of a child’s progress...",
                            Name = "Parent",
                            UpdatedAt = new DateTime(2025, 1, 7, 8, 31, 10, 171, DateTimeKind.Utc).AddTicks(1630)
                        },
                        new
                        {
                            RoleId = new Guid("28c99a2a-e593-4353-8dc2-cb83fc1ebfea"),
                            CodeName = (short)4,
                            CreatedAt = new DateTime(2025, 1, 7, 8, 31, 10, 171, DateTimeKind.Utc).AddTicks(1630),
                            Description = "Access to tour details...",
                            Name = "Student",
                            UpdatedAt = new DateTime(2025, 1, 7, 8, 31, 10, 171, DateTimeKind.Utc).AddTicks(1630)
                        });
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<Guid?>("CognitoUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("cognito_uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DefaultProfile")
                        .HasColumnType("uuid")
                        .HasColumnName("default_profile");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("CognitoUuid")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_cognito_uuid");

                    b.HasIndex("DefaultProfile")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_email");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("725f77b0-258a-4a92-827a-f5c4adfcba49"),
                            CognitoUuid = new Guid("e95e0498-b0c1-700b-bb76-f571c5ec3f7c"),
                            CreatedAt = new DateTime(2025, 1, 7, 8, 31, 10, 171, DateTimeKind.Utc).AddTicks(1750),
                            Email = "yangqingyan0@gmail.com",
                            UpdatedAt = new DateTime(2025, 1, 7, 8, 31, 10, 171, DateTimeKind.Utc).AddTicks(1750)
                        });
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Profile", b =>
                {
                    b.HasOne("InnovateFuture.Domain.Entities.Profile", "InvitedByProfile")
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InnovateFuture.Domain.Entities.Organisation", "Organisation")
                        .WithMany("Profiles")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InnovateFuture.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InnovateFuture.Domain.Entities.Profile", "SupervisedByProfile")
                        .WithMany()
                        .HasForeignKey("SupervisedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InnovateFuture.Domain.Entities.User", "User")
                        .WithMany("Profiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvitedByProfile");

                    b.Navigation("Organisation");

                    b.Navigation("Role");

                    b.Navigation("SupervisedByProfile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.User", b =>
                {
                    b.HasOne("InnovateFuture.Domain.Entities.Profile", null)
                        .WithOne()
                        .HasForeignKey("InnovateFuture.Domain.Entities.User", "DefaultProfile")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Organisation", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.User", b =>
                {
                    b.Navigation("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
