// <auto-generated />
using System;
using InnovateFuture.Domain.Enums;
using InnovateFuture.Infrastructure.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InnovateFuture.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250209074608_RemoveRoleTableUpdateRoleColumnToRoleEnumType")]
    partial class RemoveRoleTableUpdateRoleColumnToRoleEnumType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "role_enum", new[] { "undefined_role", "platform_admin", "org_admin", "org_manager", "org_teacher", "parent", "student" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Organisation", b =>
                {
                    b.Property<Guid>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("org_name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<short?>("Subscription")
                        .HasColumnType("smallint")
                        .HasColumnName("subscription");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website_url");

                    b.HasKey("OrgId");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<Guid?>("Inviter")
                        .HasColumnType("uuid")
                        .HasColumnName("inviter");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_confirmed");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<RoleEnum>("Role")
                        .HasColumnType("role_enum")
                        .HasColumnName("role");

                    b.Property<Guid?>("Supervisor")
                        .HasColumnType("uuid")
                        .HasColumnName("supervisor");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ProfileId");

                    b.HasIndex("Inviter");

                    b.HasIndex("OrgId");

                    b.HasIndex("Supervisor");

                    b.HasIndex("UserId", "Role", "OrgId")
                        .IsUnique()
                        .HasDatabaseName("IX_Profiles_user_id_role_org_id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<Guid?>("CognitoUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("cognito_uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DefaultProfile")
                        .HasColumnType("uuid")
                        .HasColumnName("default_profile");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("CognitoUuid")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_cognito_uuid");

                    b.HasIndex("DefaultProfile")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Profile", b =>
                {
                    b.HasOne("InnovateFuture.Domain.Entities.Profile", "InviterProfile")
                        .WithMany()
                        .HasForeignKey("Inviter")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InnovateFuture.Domain.Entities.Organisation", "Organisation")
                        .WithMany("Profiles")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InnovateFuture.Domain.Entities.Profile", "SupervisorProfile")
                        .WithMany()
                        .HasForeignKey("Supervisor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InnovateFuture.Domain.Entities.User", "User")
                        .WithMany("Profiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InviterProfile");

                    b.Navigation("Organisation");

                    b.Navigation("SupervisorProfile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.User", b =>
                {
                    b.HasOne("InnovateFuture.Domain.Entities.Profile", null)
                        .WithOne()
                        .HasForeignKey("InnovateFuture.Domain.Entities.User", "DefaultProfile")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Organisation", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.User", b =>
                {
                    b.Navigation("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
