// <auto-generated />
using System;
using InnovateFuture.Domain.Enums;
using InnovateFuture.Infrastructure.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InnovateFuture.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250214104358_CreateActivityDayTourTable")]
    partial class CreateActivityDayTourTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enrollment_status_enum", new[] { "undefined_enrollment", "enrolled", "dropped", "completed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "org_status_enum", new[] { "undefined_org_status", "pending", "active", "suspended" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "role_enum", new[] { "undefined_role", "platform_admin", "org_admin", "org_manager", "org_teacher", "parent", "student" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "subscription_enum", new[] { "undefined_subscription", "free", "basic", "premium" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tour_status_enum", new[] { "undefined_tour", "draft", "published", "active", "updated", "completed", "canceled" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ActivityDay", b =>
                {
                    b.Property<Guid>("ActivitiesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DaysBelongId")
                        .HasColumnType("uuid");

                    b.HasKey("ActivitiesId", "DaysBelongId");

                    b.HasIndex("DaysBelongId");

                    b.ToTable("ActivityDay");
                });

            modelBuilder.Entity("ActivityProfile", b =>
                {
                    b.Property<Guid>("AssignedActivitiesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeachersAssignedId")
                        .HasColumnType("uuid");

                    b.HasKey("AssignedActivitiesId", "TeachersAssignedId");

                    b.HasIndex("TeachersAssignedId");

                    b.ToTable("ActivityProfile");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CoverImgUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamptz");

                    b.Property<TourStatusEnum>("Status")
                        .HasColumnType("tour_status_enum");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Day", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CoverImgUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<TourStatusEnum>("Status")
                        .HasColumnType("tour_status_enum");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("TourId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.HasIndex("TourId");

                    b.ToTable("Days");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<OrgStatusEnum>("OrgStatus")
                        .HasColumnType("org_status_enum");

                    b.Property<SubscriptionEnum>("Subscription")
                        .HasColumnType("subscription_enum");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("Inviter")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<RoleEnum>("Role")
                        .HasColumnType("role_enum");

                    b.Property<Guid?>("Supervisor")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Inviter");

                    b.HasIndex("OrgId");

                    b.HasIndex("Role");

                    b.HasIndex("Supervisor");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Role", "OrgId")
                        .IsUnique()
                        .HasDatabaseName("IX_Profiles_user_id_role_org_id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.StudentTourEnrollment", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TourId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("timestamptz");

                    b.Property<EnrollmentStatusEnum>("Status")
                        .HasColumnType("enrollment_status_enum");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("WithdrawalDate")
                        .HasColumnType("timestamptz");

                    b.HasKey("ProfileId", "TourId");

                    b.HasIndex("TourId");

                    b.ToTable("StudentTourEnrollments");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Tour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CoverImgUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("Leader")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamptz");

                    b.Property<TourStatusEnum>("Status")
                        .HasColumnType("tour_status_enum");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Leader");

                    b.HasIndex("OrgId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("DefaultProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("IdpSubject")
                        .HasColumnType("uuid");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultProfileId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_email");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ActivityDay", b =>
                {
                    b.HasOne("InnovateFuture.Domain.Entities.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InnovateFuture.Domain.Entities.Day", null)
                        .WithMany()
                        .HasForeignKey("DaysBelongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ActivityProfile", b =>
                {
                    b.HasOne("InnovateFuture.Domain.Entities.Activity", null)
                        .WithMany()
                        .HasForeignKey("AssignedActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InnovateFuture.Domain.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("TeachersAssignedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Activity", b =>
                {
                    b.HasOne("InnovateFuture.Domain.Entities.Organisation", "Organisation")
                        .WithMany("Activities")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Day", b =>
                {
                    b.HasOne("InnovateFuture.Domain.Entities.Organisation", "Organisation")
                        .WithMany("Days")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InnovateFuture.Domain.Entities.Tour", "Tour")
                        .WithMany("Days")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Profile", b =>
                {
                    b.HasOne("InnovateFuture.Domain.Entities.Profile", "InviterProfile")
                        .WithMany()
                        .HasForeignKey("Inviter")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InnovateFuture.Domain.Entities.Organisation", "Organisation")
                        .WithMany("Profiles")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InnovateFuture.Domain.Entities.Profile", "SupervisorProfile")
                        .WithMany()
                        .HasForeignKey("Supervisor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InnovateFuture.Domain.Entities.User", "User")
                        .WithMany("Profiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InviterProfile");

                    b.Navigation("Organisation");

                    b.Navigation("SupervisorProfile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.StudentTourEnrollment", b =>
                {
                    b.HasOne("InnovateFuture.Domain.Entities.Profile", "Student")
                        .WithMany("StudentTourEnrollments")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InnovateFuture.Domain.Entities.Tour", "Tour")
                        .WithMany("StudentTourEnrollments")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Tour", b =>
                {
                    b.HasOne("InnovateFuture.Domain.Entities.Profile", "LeaderProfile")
                        .WithMany("LeadingTours")
                        .HasForeignKey("Leader")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InnovateFuture.Domain.Entities.Organisation", "Organisation")
                        .WithMany("Tours")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaderProfile");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.User", b =>
                {
                    b.HasOne("InnovateFuture.Domain.Entities.Profile", null)
                        .WithOne()
                        .HasForeignKey("InnovateFuture.Domain.Entities.User", "DefaultProfileId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("InnovateFuture.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("InnovateFuture.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("InnovateFuture.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Organisation", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Days");

                    b.Navigation("Profiles");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Profile", b =>
                {
                    b.Navigation("LeadingTours");

                    b.Navigation("StudentTourEnrollments");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Tour", b =>
                {
                    b.Navigation("Days");

                    b.Navigation("StudentTourEnrollments");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.User", b =>
                {
                    b.Navigation("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
