// <auto-generated />
using System;
using InnovateFuture.Infrastructure.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InnovateFuture.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

<<<<<<< HEAD
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<Guid?>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid?>("SupervisedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("supervised_by");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ProfileId");

                    b.HasIndex("InvitedBy");

                    b.HasIndex("OrgId");

                    b.HasIndex("RoleId");

                    b.HasIndex("SupervisedBy");

                    b.HasIndex("UserId", "RoleId", "OrgId")
                        .IsUnique()
                        .HasDatabaseName("IX_Profiles_user_id_role_id_org_id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<short>("CodeName")
                        .HasColumnType("smallint")
                        .HasColumnName("code_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
=======
                    b.Property<string>("ProductName")
>>>>>>> eace9c9ac9e23d482f1d2a3e2e03b7e7ff7d0a1b
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.OrderItem", b =>
                {
<<<<<<< HEAD
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<Guid?>("CognitoUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("cognito_uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DefaultProfile")
                        .HasColumnType("uuid")
                        .HasColumnName("default_profile");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("CognitoUuid")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_cognito_uuid");

                    b.HasIndex("DefaultProfile")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Profile", b =>
                {
                    b.HasOne("InnovateFuture.Domain.Entities.Profile", "InvitedByProfile")
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InnovateFuture.Domain.Entities.Organisation", "Organisation")
                        .WithMany("Profiles")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InnovateFuture.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InnovateFuture.Domain.Entities.Profile", "SupervisedByProfile")
                        .WithMany()
                        .HasForeignKey("SupervisedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InnovateFuture.Domain.Entities.User", "User")
                        .WithMany("Profiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvitedByProfile");

                    b.Navigation("Organisation");

                    b.Navigation("Role");

                    b.Navigation("SupervisedByProfile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.User", b =>
                {
                    b.HasOne("InnovateFuture.Domain.Entities.Profile", null)
                        .WithOne()
                        .HasForeignKey("InnovateFuture.Domain.Entities.User", "DefaultProfile")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Organisation", b =>
=======
                    b.HasOne("InnovateFuture.Domain.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InnovateFuture.Domain.Entities.Order", b =>
>>>>>>> eace9c9ac9e23d482f1d2a3e2e03b7e7ff7d0a1b
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
