name: PR Preview - Deployment
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: The Pull Request number
        required: true
        type: number
  pull_request:
    branches:
      - dev

permissions:
  id-token: write # This is required for requesting the JWT (OIDC)
  contents: read
  pull-requests: write

jobs:   
  ci-pipeline:
    uses: ./.github/workflows/jobs/build-and-push.yml
    with:
      environment: Development
      pr_number: ${{ inputs.pr_number || github.event.pull_request.number }}
    secrets:
      AWS_REGION: ${{ secrets.CENTRAL_ECR_REGION }}
      OIDC_ROLE_ARN : arn:aws:iam::${{ secrets.AWS_DEV_ACCOUNT }}:role/oidc-${{ vars.REPO_ORG_ABBR }}-${{ vars.REPO_BACKEND }}
      ECR_REGISTRY: ${{ secrets.AWS_PROD_ACCOUNT }}
      ECR_REPO_BASE: ${{ secrets.CENTRAL_ECR_REPO_BASE }}
      ECR_REPO_PUBLISH: ${{ secrets.CENTRAL_ECR_REPO_PUBLISH }}
