name: PR Discord Notification

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create PR notification
        if: github.event.pull_request.draft == false
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          thread-id: "1330422313769893938"
          content: ""
          embed-title: ${{ github.event.pull_request.title }}
          embed-description: |
            **Repository**
            ${{ github.repository }}

            **Ref**
            refs/pull/${{ github.event.pull_request.number }}/merge

            **Event** - pull_request
            #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}

            **Triggered by**
            ${{ github.event.pull_request.user.login }}

            **Workflow**
            PR Discord Notification
          embed-url: ${{ github.event.pull_request.html_url }}
          embed-color: "5793E6"
          wait: true

      - name: Create PR merged notification
        if: github.event.pull_request.merged == true && github.event.pull_request.draft == false
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          thread-id: "1330422313769893938"
          content: ""
          embed-title: "Success: PR Discord Notification"
          embed-description: |
            **Repository**
            ${{ github.repository }}

            **Ref**
            refs/pull/${{ github.event.pull_request.number }}/merge

            **Event** - pull_request
            #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}

            **Triggered by**
            ${{ github.event.pull_request.merged_by.login }}

            **Workflow**
            PR Discord Notification
          embed-url: ${{ github.event.pull_request.html_url }}
          embed-color: "3BA55D"
          wait: true